service: frontend
app: northernlife
org: nossey

provider:
  name: aws
  runtime: nodejs10.x

  stage: production
  region: ap-northeast-1
  environment:
    NODE_ENV: production

package:
  exclude:
    - src/**

functions:
  northernlife-renderer:
    handler: handler.render
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  name: northernlife
  customDomain:
    domainName: 'northernlife.net'
    certificateName: '*.northernlife.net'
    basePath: ''
    stage: production
    createRoute53Record: true
