version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app/
hooks:
  ApplicationStop:
    - location: scripts/shutdown_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/reboot_server.sh
      timeout: 1200
      runas: ec2-user
