version: 0.0
os: linux
files:
  - source: ./
    destination: ./
hooks:
  BeforeInstall:
    - location: ./scripts/shutdown_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: ./scripts/reboot_server.sh
      timeout: 300
      runas: ec2-user
