version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app
hooks:
  BeforeInstall:
    - location: ./scripts/terminate_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: ./scripts/reboot_server.sh
      timeout: 300
      runas: ec2-user
