version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: ./scripts/shutdown_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./scripts/reboot_server.sh
      timeout: 300
      runas: root
