version: "3"
services:
  frontend:
    build: ./frontend
    image: nossey/northernlife-frontend
    ports:
      - '3000'
  backend:
    build: ./backend
    image: nossey/northernlife-backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - '9000'