version: "3"
services:
  frontend:
    build: ./frontend
    image: nossey/northernlife-frontend:latest
    ports:
      - '80:3000'
  backend:
    build: ./backend
    image: nossey/northernlife-backend:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - '9000:9000'