version: "3"
services:
  frontend:
    build: ./frontend
    image: nossey/northernlife-frontend:latest
    ports:
      - '8000:3000'
    environment:
      - API_BASE_URL=${API_BASE_URL}
  backend:
    build: ./backend
    image: nossey/northernlife-backend:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - AWS_REGION=${AWS_REGION}
    ports:
      - '9000:9000'
