version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
  aws-cli: circleci/aws-cli@0.1
  docker: circleci/docker@1.2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.14
    working_directory: /tmp/deployment

jobs:
  pre-deploy:
    executor: default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          command: |
            set +e
            aws deploy get-application --application-name northernlife
            if [ $? -ne 0 ]; then
              set -e
              echo "No application named northernlife found. Trying to create a new one"
              aws deploy create-application --application-name northernlife
            else
              set -e
              echo "Application named northernlife already exists. Skipping creation."
            fi
          name: ensure-application-created
      - run:
          command: |
            set +e
            aws deploy get-deployment-group \
              --application-name northernlife \
              --deployment-group-name northernlife 
            if [ $? -ne 0 ]; then
              set -e
              echo "No deployment group named northernlife found. Trying to create a new one"
              aws deploy create-deployment-group \
                --application-name northernlife \
                --deployment-group-name northernlife \
                --service-role-arn arn:aws:iam::854919677002:role/northernlife-codedeploy
            else
              set -e
              echo "Deployment group named northernlife already exists. Skipping creation."
            fi
          name: ensure-deployment-created
    
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - docker/publish:
          image: nossey/northernlife-frontend
          docker-context: ./frontend
          path: ./frontend
          tag: latest
          name: build-frontend
      - docker/publish:
          image: nossey/northernlife-backend
          docker-context: ./backend
          path: ./backend
          tag: latest
          name: build-backend
      - pre-deploy:
          requires:
            - build-frontend
            - build-backend
          filters:
            branches:
              only: master
      - aws-code-deploy/deploy:
           application-name: northernlife
           bundle-bucket: northernlife-circleci-deploy
           bundle-key: deployment
           deployment-group: northernlife
           service-role-arn: northernlife-codedeploy
           requires:
            - pre-deploy
           filters:
            branches:
              only: master