basePath: /api/v1
definitions:
  model.ErrorMessage:
    properties:
      message:
        type: string
    type: object
  model.Login:
    properties:
      password:
        type: string
      userID:
        type: string
    required:
    - password
    - userID
    type: object
  model.LoginSuccessMessage:
    properties:
      expired_at:
        type: string
      token:
        type: string
    type: object
  model.Post:
    properties:
      body:
        type: string
      created_at:
        type: string
      id:
        type: string
      plain_body:
        type: string
      published:
        type: boolean
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  model.PostCreateBody:
    properties:
      body:
        type: string
      plain_body:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    required:
    - body
    - plain_body
    - tags
    - title
    type: object
  model.PostCreateResult:
    properties:
      post_id:
        type: string
    type: object
  model.PostListModel:
    properties:
      per_page_count:
        type: integer
      posts:
        items:
          $ref: '#/definitions/model.Post'
        type: array
      total_count:
        type: integer
    type: object
  model.TagCreateFailResult:
    properties:
      message:
        type: string
    type: object
  model.TagCreatedResult:
    properties:
      tagName:
        type: string
    type: object
  model.UnauthorizedMessage:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  model.User:
    properties:
      userID:
        type: string
    type: object
host: localhost:9000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/model.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginSuccessMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.UnauthorizedMessage'
      summary: Login
      tags:
      - Auth
  /auth/user:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      security:
      - ApiKeyAuth: []
      summary: Login
      tags:
      - Auth
  /posts:
    get:
      consumes:
      - application/json
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PostListModel'
      summary: Get posts with pagination
      tags:
      - Posts
    post:
      consumes:
      - application/json
      parameters:
      - description: Post Data
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/model.PostCreateBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PostCreateResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.UnauthorizedMessage'
      security:
      - ApiKeyAuth: []
      summary: Create single post
      tags:
      - Posts
  /posts/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Post'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorMessage'
      summary: Get single post with specific id
      tags:
      - Posts
  /tags:
    get:
      consumes:
      - application/json
      description: Get all tags
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: Get tags
      tags:
      - Tags
    post:
      consumes:
      - application/json
      description: Create a new tag
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TagCreatedResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.TagCreateFailResult'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.UnauthorizedMessage'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/model.TagCreateFailResult'
      summary: Create tag
      tags:
      - Tags
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
